---
- name: Install required packages for rabbitmq
  hosts: vizrabbit
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: curl,gnupg,apt-transport-https
        state: present

    - name: Add RabbitMQ GPG key
      shell: |
        curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" |
        gpg --dearmor |
        tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null

    - name: Add RabbitMQ Erlang GPG key
      shell: |
        curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key |
        gpg --dearmor |
        tee /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg > /dev/null

    - name: Add RabbitMQ Server GPG key
      shell: |
        curl -1sLf https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key |
        gpg --dearmor |
        tee /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg > /dev/null        

    - name: Add RabbitMQ repository to sources.list
      blockinfile:
        dest: /etc/apt/sources.list.d/rabbitmq.list
        block: |
          ## Provides modern Erlang/OTP releases from a Cloudsmith mirror
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main
          # another mirror for redundancy
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/debian bookworm main

          ## Provides RabbitMQ from a Cloudsmith mirror
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main
          # another mirror for redundancy
          deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main
          deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/debian bookworm main
        create: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Erlang packages
      shell: |
        sudo apt-get install -y erlang-base \
        erlang-asn1 erlang-crypto erlang-eldap erlang-ftp erlang-inets \
        erlang-mnesia erlang-os-mon erlang-parsetools erlang-public-key \
        erlang-runtime-tools erlang-snmp erlang-ssl \
        erlang-syntax-tools erlang-tftp erlang-tools erlang-xmerl

    - name: Install rabbitmq-server and its dependencies
      shell: |
        sudo apt-get install rabbitmq-server -y --fix-missing   